// Builds the JavaScript without the package ever losing its entry point.
//
// `rimraf dist/plugin && vite build` leaves a window — the length of a Vite
// build — in which anything linked to this checkout fails to resolve the
// package. Building somewhere else and moving the result into place shrinks
// that window to a rename.

import { cpSync, mkdirSync, rmSync, renameSync, existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';

import { buildId } from './build-id.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const staging = join(root, 'dist', '.build');
const previous = join(root, 'dist', '.previous');

rmSync(staging, { recursive: true, force: true });
rmSync(previous, { recursive: true, force: true });
mkdirSync(staging, { recursive: true });

// vite.config.ts reads this for both the bundle and the declaration output;
// the dts plugin has its own outDir and would otherwise write into dist.
process.env.MOG_OUT_DIR = staging;
try {
  // `root` explicitly: Vite takes it from process.cwd() otherwise, and this
  // script can be run from anywhere. Without it there is no vite.config.ts —
  // no dts plugin, no lib entry, no `@parser` rewrite.
  await build({ root });
} catch (error) {
  rmSync(staging, { recursive: true, force: true });
  throw error;
}

// The public parser entry ships as source: it is plain JavaScript beside a
// hand-written .d.ts, and bundling it would only reintroduce the alias
// rewriting its relative import exists to avoid.
const parser = join(staging, 'parser');
mkdirSync(parser, { recursive: true });
for (const name of ['index.js', 'index.d.ts', 'check.js']) {
  cpSync(join(root, 'src', 'parser-entry', name), join(parser, name));
}

// The digest of the tree the native binary was built from, for the entry to
// compare against what the binary reports.
writeFileSync(
  join(parser, 'build-id.js'),
  `// Generated by scripts/build-js.mjs — the tree this JavaScript was built from.\nexport const BUILD_ID = ${JSON.stringify(buildId(root))};\n`
);

// Swap directory by directory, moving the old build aside rather than deleting
// it. A recursive delete is not atomic — it empties the directory in place,
// so a consumer can resolve `dist/plugin` and then read a half-removed
// index.js. A rename cannot be observed half-done, and it keeps the previous
// build intact in case the second rename fails.
for (const name of ['plugin', 'parser']) {
  const live = join(root, 'dist', name);
  const next = join(staging, name);
  if (!existsSync(next)) continue;

  if (existsSync(live)) {
    mkdirSync(previous, { recursive: true });
    renameSync(live, join(previous, name));
  }
  renameSync(next, live);
}

rmSync(staging, { recursive: true, force: true });
rmSync(previous, { recursive: true, force: true });
