// Builds the JavaScript without the package ever losing its entry point.
//
// `rimraf dist/plugin && vite build` leaves a window — the length of a Vite
// build — in which anything linked to this checkout fails to resolve the
// package. Building somewhere else and moving the result into place shrinks
// that window to a rename.

import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { cpSync, mkdirSync, rmSync, renameSync, existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildId } from './build-id.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const staging = join(root, 'dist', '.build');
const trash = join(root, 'dist', '.trash');

rmSync(staging, { recursive: true, force: true });
rmSync(trash, { recursive: true, force: true });
mkdirSync(staging, { recursive: true });

// vite.config.ts reads this for both the bundle and the declaration output;
// the dts plugin has its own outDir and would otherwise write into dist.
// Resolved from the package rather than spawned by name: this runs as a plain
// node script, so node_modules/.bin is not necessarily on PATH. Vite's exports
// map does not expose its bin, so go via its package.json.
const require = createRequire(import.meta.url);
const vitePackage = require.resolve('vite/package.json');
const viteBin = join(dirname(vitePackage), require(vitePackage).bin.vite);

const build = spawnSync(process.execPath, [viteBin, 'build'], {
  cwd: root,
  stdio: 'inherit',
  env: { ...process.env, MOG_OUT_DIR: staging },
});
if (build.status !== 0) {
  rmSync(staging, { recursive: true, force: true });
  process.exit(build.status ?? 1);
}

// The public parser entry ships as source: it is plain JavaScript beside a
// hand-written .d.ts, and bundling it would only reintroduce the alias
// rewriting its relative import exists to avoid.
const parser = join(staging, 'parser');
mkdirSync(parser, { recursive: true });
for (const name of ['index.js', 'index.d.ts', 'check.js']) {
  cpSync(join(root, 'src', 'parser-entry', name), join(parser, name));
}

// The digest of the tree the native binary was built from, for the entry to
// compare against what the binary reports.
writeFileSync(
  join(parser, 'build-id.js'),
  `// Generated by scripts/build-js.mjs — the tree this JavaScript was built from.\nexport const BUILD_ID = ${JSON.stringify(buildId(root))};\n`
);

// Swap directory by directory, each one a rename: the entry point is either the
// old build or the new one, never absent.
for (const name of ['plugin', 'parser']) {
  const live = join(root, 'dist', name);
  const next = join(staging, name);
  if (!existsSync(next)) continue;

  if (existsSync(live)) {
    mkdirSync(trash, { recursive: true });
    renameSync(live, join(trash, name));
  }
  renameSync(next, live);
}

rmSync(staging, { recursive: true, force: true });
rmSync(trash, { recursive: true, force: true });
